# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337
  user_dir: ???

checkpoint:
  save_interval: 1000000
  save_interval_updates: 2000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer
  maximize_best_checkpoint_metric: false

distributed_training:
  ddp_backend: c10d
  find_unused_parameters: true
  distributed_world_size: 8
  distributed_port: 29671
  nprocs_per_node: 8

task:
  _name: av_hubert_pretraining
  is_s2s: false
  data: /checkpoint/wnhsu/data/easycom/processed/manifest
  label_dir: /checkpoint/wnhsu/data/easycom/processed/manifest
  normalize: true  # must be consistent with pre-training
  labels: ["ltr"]
  single_target: true
  fine_tuning: true
  stack_order_audio: 4
  max_sample_size: 500
  modalities: ["video","audio"]
  image_aug: true
  pad_audio: true
  random_crop: false
  noise_prob: 0.25
  noise_snr: 0
  noise_wav: /checkpoint/wnhsu/data/avhubert_manifest/musan/all-for-training

dataset:
  num_workers: 6
  max_tokens: 1000
  validate_after_updates: 0
  validate_interval: 1000000
  validate_interval_updates: 2000
  train_subset: train
  valid_subset: valid

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 30000
  lr: [0.0005]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.33,0,0.67]
  final_lr_scale: 0.05

model:
  _name: av_hubert_ctc
  w2v_path: ???
  apply_mask: false
  mask_selection: static
  # mask_length: 10
  mask_other: 0
  # mask_prob: 0.75
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
  feature_grad_mult: 1.0
  freeze_finetune_updates: 24000

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
